### ISSUE TITLE
nessus-agent outdated

### ISSUE THREAD

**Issue by macinnisrob** [teknowledgist/Chocolatey-packages#101]
Package id: nessus-agent

Current package version: 1.6.1
Version to update to: 1.6.2

**Comment by macinnisrob** [comment]
Frustratingly, it seems that Tenable is deleting the old pages that host their downloads once they publish a new version.

Which means that choco responds with an error as soon as a new Nessus version is published:
```
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url '<a href='https://www.tenable.com/downloads/api/v1/public/pages/nessus-agents/downloads/22697/download?i_agree_to_tenable_license_agreement=true'>https://www.tenable.com/downloads/api/v1/public/pages/nessus-agents/downloads/22697/download?i_agree_to_tenable_license_agreement=true</a>'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
```

**Comment by teknowledgist** [comment]
Just submitted the updated package.  Sorry this keeps coming up.  It's these frequent updates that cause problems.  Maybe it will give me the kick in the pants to finally, fully automate update checks instead of manually running the updater every so often.  😮

**Comment by macinnisrob** [comment]
Thanks! No worries about the timing. But yeah, it seems like it might be a good use case for Actions.
