### ISSUE TITLE
QGIS Package: URL to MSI file faulty

### ISSUE THREAD

**Issue by TinoM** [teknowledgist/Chocolatey-packages#107]
Hi,

it seems the the current version of the Choco QGIS 3.38.1 package is broken.
It references a local path to the MSI file instead of the public URL:

https://github.com/teknowledgist/Chocolatey-packages/blob/master/automatic/qgis/tools/chocolateyinstall.ps1#L13

**Comment by teknowledgist** [comment]
Sorry about that!  I didn't fix the v3.38.1 package, but later versions are corrected.
