### ISSUE TITLE
Download DraftSight 2018 SP3 now

### ISSUE THREAD

**Issue by basictheprogram** [teknowledgist/Chocolatey-packages#14]
https://www.3ds.com/products-services/draftsight-cad-software/free-download/

**Comment by teknowledgist** [comment]
Submitted the package for the new release.  I have not tested it yet, but I can't imagine they made too many changes in the installation process.

**Comment by basictheprogram** [comment]
Thanks! 

I started the work work and got pulled into fighting a fire.
