### ISSUE TITLE
[notepad3] Update for 5.19.630.2381

### ISSUE THREAD

**Issue by leonghui** [teknowledgist/Chocolatey-packages#16]
Hi there,

There is a new release since July 1 2019:
https://github.com/rizonesoft/Notepad3/releases/tag/RELEASE_5.19.630.2381

**Comment by teknowledgist** [comment]
Hi.  I saw that it has updated, but the site has been redesigned to prevent automatic scraping.  I haven't had a chance to manually update the package until now.  I've just submitted the package, and it should be approved shortly.
