### ISSUE TITLE
Cannot install 32 bits versions of MATLAB Compiler Runtime

### ISSUE THREAD

**Issue by jljouannic** [teknowledgist/Chocolatey-packages#17]
`mcr-r2014b` and `mcr-r2015a` packages do not work if `cinst` is run with `--forcex86` option.
Here is, for example, the error message returned after running `cinst -dvy --forcex86 mcr-r2014b`:
```
ERROR: Cannot process argument transformation on parameter 'file'. Cannot convert value to type System.String.
 at <ScriptBlock>, C:\ProgramData\chocolatey\lib\mcr-r2014b\tools\chocolateyinstall.ps1: line 45
at <ScriptBlock>, C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1: line 49
at <ScriptBlock>, <No file>: line 1
```

Here is the command used to find the `setup.exe` file among the extracted file of MCR installer:
```
$Installer = (Get-ChildItem $WorkSpace -Include 'setup.exe' -Recurse).fullname
```

The 32 bits install fails because the win32 MCR installer contains two `setup.exe` files instead of a single one in the 64 bits MCR installer.

**Comment by teknowledgist** [comment]
I've pushed the 2015b package and pushed updates for the other two.  Thank you for the fixes/cleanup.
