### ISSUE TITLE
VSTOR2010 - Fail due to reg path non existence under O365

### ISSUE THREAD

**Issue by Chirishman** [teknowledgist/Chocolatey-packages#20]
The package fails to work on systems with Office 365 deployed because the error action is stop and that reg path doesn't exist on click-to-run instead of MSI installs of office.

**Comment by teknowledgist** [comment]
This package is designed to only warn if an install of Office is not found.  It shouldn't be failing unless the installer itself encounters a problem.

I finally got access to install Office365 to test this, and at least on my test machine all the same registry keys are created and exist.  This vstor2010 package installed just fine after Office365 was installed, so unless it can be repeated, I don't know how to fix the problem experienced.
