### ISSUE TITLE
choco-font-extensions cannot call method on null-valued expression

### ISSUE THREAD

**Issue by cprivite** [teknowledgist/Chocolatey-packages#22]
Ok, so I use this for the inconsolata package on chocolatey. When I submitted the newer version using this module a few months ago it worked great. Now when I try to uninstall using Uninstall-ChocolateyFont I get the following error:

> WARNING: An error occured removing 'Inconsolata-Regular.ttf'.
> ERROR: You cannot call a method on a null-valued expression.
> inconsolata uninstall not successful.
> Error while running 'C:\ProgramData\chocolatey\lib\inconsolata\tools\chocolateyUninstall.ps1'.
>  See log for details.
> inconsolata not uninstalled. An error occurred during uninstall:
>  inconsolata uninstall not successful.
> 
> Chocolatey uninstalled 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  - inconsolata (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\inconsolata\tools\chocolateyUninstall.ps1'.
>  See log for details.

The chocolatey.log adds:

```
2019-12-13 19:42:35,632 3272 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\inconsolata\tools\chocolateyUninstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
2019-12-13 19:42:35,642 3272 [DEBUG] - Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
2019-12-13 19:42:35,703 3272 [DEBUG] - Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'

```

Have you seen this before? I don't understand what's going on.

While the above error was from an uninstall on a non-existant font. I'm also getting the same error trying to upgrade an existing font. Is there a particular methodology you're supposed to use during upgrades that I'm not following? 

Here's my entire chocolateyInstall.ps1 for the inconsolata package:
```
$ErrorActionPreference = 'Stop'; # stop on all errors
$toolsDir   = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

$url1 = 'https://github.com/googlefonts/Inconsolata/raw/v3.000/fonts/ttf/Inconsolata-Regular.ttf'
$url2 = 'https://github.com/googlefonts/Inconsolata/raw/v3.000/fonts/ttf/Inconsolata-Bold.ttf'

Get-ChocolateyWebFile `
  -PackageName $env:ChocolateyPackageName `
  -FileFullPath $toolsDir\Inconsolata-Regular.ttf `
  -Url $url1 `
  -Checksum '127875D255D4C5973CA57267A43BB9D1C04397E6C7D236984A595B6CDCB12B7C' `
  -ChecksumType SHA256 `

Get-ChocolateyWebFile `
  -PackageName $env:ChocolateyPackageName `
  -FileFullPath $toolsDir\Inconsolata-Bold.ttf `
  -Url $url2 `
  -Checksum '263FAA57F6C00C43A04E77DF7ABD5CB5CD4AAE9F93507002C1217E02641FC7E6' `
  -ChecksumType SHA256 `


Install-ChocolateyFont $toolsDir -multiple
```

I've tried changing the last bit to the following but that just uninstalls the fonts and still errors out trying to install the new one:

```
Uninstall-ChocolateyFont Inconsolata-Regular.ttf
Uninstall-ChocolateyFont Inconsolata-Bold.ttf
Install-ChocolateyFont $toolsDir -multiple
```

What am I missing?

**Comment by teknowledgist** [comment]
@cprivite I'm sorry you are encountering a problem.  Looking through the code, I am not seeing where the issue could be occurring.  I'll have to do some testing myself, but it will be a day or two before I will get a chance.

Are you seeing the same `ERROR: You cannot call a method on a null-valued expression.` for the (install portion of the) upgrade as for the uninstall (in your first example)?

Also, do you experience the same issue if you uninstall/upgrade immediately after booting?  In my original testing, I think there was one odd situation where the font file was "in use" which caused problems.

**Comment by teknowledgist** [comment]
@cprivite I am not able to repeat any of the issues you are reporting.  

I tried both installing an older version in the public repository and upgrading to the latest in the repository as well as upgrading the latest in the repository to a test package I built using the code you provided above.  In both cases, I had no errors.  

Can you provide some additional information about your situation?  What release of Windows are you using?  What language version is it?  What version of Chocolatey are you using?  Do you experience this on multiple machines?  Are you using Inconsolata for for any system or application-level purposes beyond displaying text in a document?  IOW, have you set it as a menu or window font?

Thanks.

**Comment by cprivite** [comment]
Windows 10 1909 (OS Build 18363.535)
Tried both Powershell 5 and 6.
Chocolatey v0.10.15
I have only tried on one machine so far, I will try other machiens and report back. 
I am not using inconsolata in any system or application level purposes beyond displaying text.

**Comment by teknowledgist** [comment]
@cprivite Were you able to repeat the problems with your inconsolata package on other machines?  If not, I'm going to close this as an unknown one-off problem with your testing machine because I have been unable to observe the issue.

**Comment by cprivite** [comment]
I was unable to reproduce on a new machine. I'm ok closing this.

**Comment by Cirzen** [comment]
I'm wondering if this package is running into the same issue: https://chocolatey.org/packages/jetbrainsmono#comment-5067829733
The issue written up there seems to be to do with a hashing check gone wrong. Is that something the extension is doing?
