### ISSUE TITLE
[chocolatey-font-helpers.extension] Error for subsequent font installs when using Boxstarter

### ISSUE THREAD

**Issue by flcdrg** [teknowledgist/Chocolatey-packages#42]
As mentioned in https://github.com/chocolatey/boxstarter/issues/455, because the current architecture of Boxstarter has a single PowerShell session then if multiple packages try to install fonts then they will fail when the `Add-Type` cmdlet is called by subsequent installs (as the type already exists then).

A possible mitigation would be either to [check if the type already exists](https://stackoverflow.com/questions/25730978/powershell-add-type-cannot-add-type-already-exist), or set an `-ErrorAction SilentlyContinue` on that call.

**Comment by teknowledgist** [comment]
I think I have something that will work with v0.3 that I just pushed.  Let me know either way.

**Comment by KZeronimo** [comment]
@teknowledgist check chocolatey/boxstarter#455 - from what I can tell version 0.0.3 appears broken - can you try `cinst cascadia-code-nerd-font` it was working fine for me earlier today.

**Comment by teknowledgist** [comment]
Totally my fault!  I really have no idea what I'm doing in C-sharp or even how to fully test what I've done in C-sharp.

Anyway, I think I fixed it now with version 0.0.3.1 (at least the cascadia-code-nerd-font is installing).

**Comment by teknowledgist** [comment]
[This appears to be fixed.](https://github.com/chocolatey/boxstarter/issues/455#issuecomment-720095735)
