### ISSUE TITLE
Decomposing registry key UninstallString results in Split-Path error

### ISSUE THREAD

**Issue by mdiers** [teknowledgist/Chocolatey-packages#43]
This happens when attempting "choco upgrade miktex.install" from "20.7" to "20.11".

In my case, "$key.UninstallString" has the value "C:\Users\mdiers\AppData\Local\Programs\MiKTeX\miktex/bin/x64\miktex-console.exe --start-page cleanup".

Determining "$InstallDir" from that results in an error:

`$InstallDir = split-path ($key.UninstallString.split('"')[1])`

```
PS C:\WINDOWS\system32> split-path("C:\Users\mdiers\AppData\Local\Programs\MiKTeX\miktex/bin/x64\miktex-console.exe --start-page cleanup".split('"')[1])
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:11
+ split-path("C:\Users\mdiers\AppData\Local\Programs\MiKTeX\miktex/bin/ ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCo
   mmand

```
Suggest using "$key.UninstallString" itself as argument to "split-path" when "$key.UninstallString.split('"')[1]" is null.

https://github.com/teknowledgist/Chocolatey-packages/blob/0b7a9d8d0fa11c4908762c367818cec697632ebf/automatic/miktex.install/tools/chocolateyinstall.ps1#L63
https://github.com/teknowledgist/Chocolatey-packages/blob/0b7a9d8d0fa11c4908762c367818cec697632ebf/automatic/miktex.install/tools/chocolateyinstall.ps1#L140

**Comment by teknowledgist** [comment]
Sorry about that!  In my testing, the uninstallstring always included quotes around the path.  (I also didn't realize that `split-path` would ignore the arguments in the string.)

I've fixed the code and submitted a new package to the public repository.  It might take a few hours to go through verification.

Thanks for reporting the problem.
