### ISSUE TITLE
Chimera v1.15

### ISSUE THREAD

**Issue by uwemolnar** [teknowledgist/Chocolatey-packages#50]
Hi @teknowledgist,

the new version of Chimera seems to have problems with the installer-file. The installer is not imported into the nupkg. It looks like the webpage from UCSF has changed (https://www.cgl.ucsf.edu/chimera/download.html). They have no more direct links to their software. Instead the download-link(s) seem to be associated with a py-Script (chimera-get.py), that leeds to a "License Agreement"-page. Only after confirming you can now download the sources.

Do you have any idea how to solve this issue in the update.ps1? Thanks for your help! I'll also have a look and try to solve it ;)

Have a nice day!

**Comment by teknowledgist** [comment]
@uwemolnar Thanks for the heads up that something changed.  The Chimera download had that license page before, but somehow the backend changed so the process I cooked up wouldn't work.  

I think I have it resolved now and pushed an intermediate version of the package.  It will probably take a few hours to be approved.
