### ISSUE TITLE
chocolatey-font-helpers.extension feature-request: Automagically uninstall installed fonts

### ISSUE THREAD

**Issue by cmorty** [teknowledgist/Chocolatey-packages#53]
Expected:
Uninstall installed files without having to list them

Actual:
While it is possible to install a folder it is not possible to uninstall the fonts in that folder.

Possible Solution 1:
Let `Uninstall-ChocolateyFont` scan a folder and uninstall the filenames in that folder.

Possible Solution 2: 
Log all successfully installed fonts into a file. To uninstall just reference that file. Together with the `-multi`-feature this would make maintaining font packages a lot easier, as `install.ps` and `uninstall.ps` would be the same for all packages and one would only have to add the files into the appropriate folder.

**Comment by teknowledgist** [comment]
@cmorty I am happy to say that I *finally* got around to completing this, and (IMHO) it is very nice.  [Check it out](https://community.chocolatey.org/packages/chocolatey-font-helpers.extension).

Font uninstall is **so easy** now.  Thanks for the great request.

**Comment by cmorty** [comment]
@teknowledgist : This is awesome! Thanks a lot.
