### ISSUE TITLE
LMMS fails to install when old installers present

### ISSUE THREAD

**Issue by mavhc** [teknowledgist/Chocolatey-packages#55]
For some reason my libs\lmms contained lmms-1.2.1-win32.exe and lmms-1.2.1-win64.exe as well as lmms-1.2.2-win32.exe and lmms-1.2.2-win64.exe

This caused this error

ERROR: Cannot process argument transformation on parameter 'file'. Cannot convert value to type System.String.

Because File and File64 contained 2 items, I assume.

And the package failed to install

**Comment by teknowledgist** [comment]
Hi.  The issue of older installers (sometimes) remaining and messing up the install of the new ones is something I'm working on fixing across all my packages.  I just pushed a package update for LMMS that should resolve it for everyone in the future.

In the meantime, if you delete the old, v1.2.1 files and try again, it should work.  

Sorry for the hassle.
