### ISSUE TITLE
DraftSight download URL no longer works

### ISSUE THREAD

**Issue by basictheprogram** [teknowledgist/Chocolatey-packages#6]
http://dl-ak.solidworks.com/nonsecure/draftsight/2017SP03/DraftSight64.exe results in a file not found.

<img width="992" alt="dl-ak_solidworks_com_nonsecure_draftsight_2017sp03_draftsight64_exe_and_new_issue_ _teknowledgist_chocolatey-packages_and_reporter_int_celadonsystems_com" src="https://user-images.githubusercontent.com/6723257/31549121-ce7245b6-aff2-11e7-90a5-8f5e754967e8.png">

```
$ wget http://dl-ak.solidworks.com/nonsecure/draftsight/2017SP03/DraftSight64.exe
--2017-10-13 08:45:36--  http://dl-ak.solidworks.com/nonsecure/draftsight/2017SP03/DraftSight64.exe
Resolving dl-ak.solidworks.com... 165.254.47.121, 165.254.47.137
Connecting to dl-ak.solidworks.com|165.254.47.121|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-13 08:45:36 ERROR 404: Not Found.
```

**Comment by teknowledgist** [comment]
They changed the URL (with a `-1`) and the downloads have new checksums without any change in the release notes.  I don't know what is new, but I updated the package and submitted it for moderation.
