### ISSUE TITLE
QGIS upgrade fails: "Version string portion was too short or too long."

### ISSUE THREAD

**Issue by chk1** [teknowledgist/Chocolatey-packages#71]
Upgrading QGIS from the choco package `qgis` from 3.22.1 to 3.24.1 fails with the following error:

>ERROR: Cannot convert value "" to type "System.Version". Error: "Version string portion was too short or too long."

My guess is that the version number `$LTRVersion` is no longer properly detected and currently empty in [automatic/qgis/tools/chocolateyinstall.ps1](https://github.com/teknowledgist/Chocolatey-packages/blob/master/automatic/qgis/tools/chocolateyinstall.ps1)

https://github.com/teknowledgist/Chocolatey-packages/commit/bf786285b4e1ea45e70a51ec6c220420c5552963#diff-6c6b7d8e41710ccf665625007012ac0504f143dd985e30c8c6e094d7f16c7732

The update script is looking for `.exe` links, which are not on the QGIS download page anymore, it should probably match `.msi` links instead. There's a line of text about them switching to MSI installers, I don't know when that happened.

https://github.com/teknowledgist/Chocolatey-packages/blob/master/automatic/qgis/update.ps1#L23-L28

Full log:
```
C:\WINDOWS\system32>choco upgrade qgis
Chocolatey v1.1.0
Upgrading the following packages:
qgis
By upgrading, you accept licenses for the packages.

You have qgis v3.22.1 installed. Version 3.24.1 is available based on your source(s).
Progress: Downloading QGIS 3.24.1... 100%

QGIS v3.24.1
qgis package files upgrade completed. Performing other installation steps.
The package QGIS wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): a

ERROR: Cannot convert value "" to type "System.Version". Error: "Version string portion was too short or too long."
The upgrade of qgis was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\QGIS\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - qgis (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\QGIS\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by teknowledgist** [comment]
Thank you for pointing out my oversight.  I've submitted a corrected version to the repository and -- I believe -- corrected the problem with `update.ps1`.
