### ISSUE TITLE
nessus-agent 10.2.1 CheckSums do not match published values

### ISSUE THREAD

**Issue by krajewf** [teknowledgist/Chocolatey-packages#72]
**Describe the bug**
The actual Checksum values for 10.2.1 published on the  [Nessus download page](https://www.tenable.com/downloads/nessus-agents?loginAttempted=true) do not match the checksum values provided in the nessus-agent package. The error message shows that actual Checksum value of the downloaded .msi matches the Nessus published value and not the value in the nessus-agent package.

**To Reproduce**
`choco install nessus-agent`

**Expected behavior**
Successful install of package without providing any specific checksum parameters.

**Error Message**
Here are the published Checksums from the [Nessus download page](https://www.tenable.com/downloads/nessus-agents?loginAttempted=true) 
![image](https://user-images.githubusercontent.com/11064286/201138128-e26ddaaa-5052-4986-900c-d6fc7f30f02a.png)

```
nessus-agent v10.2.1
nessus-agent package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '6ECF9CAC910B301FD74A5D22DD5480EB8ED972504AB785AA8799BE1334D1B3A5'.
Downloading nessus-agent 64 bit
  from 'https://www.tenable.com/downloads/api/v1/public/pages/nessus-agents/downloads/17738/download?i_agree_to_tenable_license_agreement=true'

Download of NessusAgent-10.2.1-x64.msi (-1 B) completed.
Error - hashes do not match. Actual value was '6ECF9CAC910B301FD74A5D22DD5480EB8ED972504AB785AA8799BE1334D1B3A5'.
ERROR: Checksum for 'C:\Users\----\AppData\Local\Temp\chocolatey\nessus-agent\10.2.1\NessusAgent-10.2.1-x64.msi' did not meet 'e59a4f3506f77b1ecdde7f92d287fa79368298146ac7487638ceb27056d6e144' for checksum type 'sha256'. Consider pass
the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of nessus-agent was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\nessus-agent\tools\chocolateyinstall.ps1'.
```

Thanks

**Comment by teknowledgist** [comment]
That is odd... I just ran the automatic updater again, and it produced the correct checksums.  

I have seen publishers replace a download with a new one without changing the version number.  (Looking at you Microsoft!)  That is the most likely scenario here.  

Anyway, I've submitted an updated package for moderation. 

Thanks for the report.
