### ISSUE TITLE
nasm - wrong package source link

### ISSUE THREAD

**Issue by Destroy666x** [teknowledgist/Chocolatey-packages#78]
**Describe the bug**
Wrong link: https://github.com/teknowledgist/Chocolatey-packages/blob/master/automatic/nasm/nasm.nuspec#L8

**To Reproduce**
-

**Expected behavior**
Correct link: https://github.com/teknowledgist/Chocolatey-packages/tree/master/automatic/nasm

**Screenshots**
-

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

**Comment by teknowledgist** [comment]
Whoops!  That's what happens when you create a package based on another and aren't careful.  😄 I'm surprised the moderators didn't catch that one.

Thanks for catching it.  An updated package has been submitted to the community repository for moderation.
