### ISSUE TITLE
DraftSight 2018 fails Automated Package Tests

### ISSUE THREAD

**Issue by basictheprogram** [teknowledgist/Chocolatey-packages#8]
DraftSight 2018 fails Automated Package Tests, the dreaded 1603 error. Snippet from the verifier.
```
 ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\Administrator\AppData\Local\Temp\chocolatey\DraftSight.2018.00\DraftSight.msi" /qn /norestart /l*v "C:\Users\Administrator\AppData\Local\Temp\chocolatey\DraftSight.2018.00.MsiInstall.log" ALLUSERS=1 ] was not successful. Exit code was '1603'. 
```
List tracking stuff that might be helpful
  1. [Old VirtualBox version requirement](https://github.com/chocolatey/chocolatey-test-environment/issues/24)
  1. [How to locate the cause of error code 1603 in a verbose MSI log file](https://blogs.msdn.microsoft.com/astebner/2005/08/01/how-to-locate-the-cause-of-error-code-1603-in-a-verbose-msi-log-file/)
  1. [Windows Server 2016 testing environment](https://github.com/chocolatey/chocolatey-test-environment/pull/23)

I think the problem is the package verifier runs [Windows Server 2012 R2](https://github.com/chocolatey/chocolatey-test-environment) and [DraftSight 2019 SP0 System Requirements](https://www.3ds.com/products-services/draftsight-cad-software/latest-version/) specifically states, "Windows Server 2012 R2 64-bit x86 (No longer supported by R2017x)".

We all know this day was coming. The Microsoft treadmill keeps moving and it's get updated or get left behind. It's the main reason I did [PR #23](https://github.com/chocolatey/chocolatey-test-environment/pull/23) on chocolatey-test-environment.

I'll do more troubleshooting. But when the vendors specifically states your operating system is not supported I think we need to petition @ferventcoder to update the operating system in chocolatey-test-environment or petition "the powers" for an exemption in the package verifier for DraftSight 2018.

*OR*

A way to identify the package verifier's operating system and support multiple testing environments.

**Comment by teknowledgist** [comment]
"*No longer supported by R2017x*" is specific to the R2017 release of DSLS (Dassault Systémes License Server).  It certainly could be that whatever made them drop 2012R2 while still supporting 2008R2 is also at play for DraftSight itself, but they don't explicitly state that.

Looking at the requirements closer, could the failure be related to the headless, test environment and limited video card and/or gui capabilities?  Am I right in assuming your 2016 test environment is non headless?

If you have sucessfully tested the rejected Draftsight 2018 package on Server 2016, and I know it works on Win7 and Win10, then I suppose I should pass a request for an exemption to the package verifier.

**Comment by basictheprogram** [comment]
I'm building Virtualbox images of 2012 R2 (fully patches), I'll test installing the package there as well as the default 2012 R2 of the chocolatey-test-environment and report back here.

**Comment by basictheprogram** [comment]
First fatal error I find
```
MSI (s) (2C:F4) [22:00:06:616]: Note: 1: 1722 2: register_FxVistaPreviewDll 3: C:\Windows\SysWOW64\ 4: regsvr32 /s "C:\Program Files\Dassault Systemes\DraftSight\bin\FxVistaPreview.dll" 

MSI (s) (2C:F4) [22:00:06:616]: Product: DraftSight 2018 SP0 x64 -- Error 1722.There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor. Action register_FxVistaPreviewDll, location: C:\Windows\SysWOW64\, command: regsvr32 /s "C:\Program Files\Dassault Systemes\DraftSight\bin\FxVistaPreview.dll"
```
Looks like this is a known problem see https://forum.solidworks.com/thread/213394

"ferventcoder/win2012r2-x64-nocm" does not have any Microsoft Visual C++ Redistributable  installed so I installed it 
```shell
C:\> choco install vcredist2015
```
The vcredist2015  really pollutes "ferventcoder/win2012r2-x64-nocm" but now draftsight 2018 installs without error.

My full patches 2012 R2 does not have  Microsoft Visual C++ Redistributable installed, yet, draftsight 2018 installs without a problem. Guessing one of the security rollup or KB installs installs or fixes what is needed by draftsight 2018?

**Comment by teknowledgist** [comment]
I discovered earlier today that vcredist 2015 was a prerequisite. I added it to the nuspec in the repository, but didn’t want to submit before your testing. 

Erich

**Comment by basictheprogram** [comment]
Does not explain why vcredist2015 is **not** needed on a fully patched 2012 R2 (or Windows10, Windows Server 2016)

**Comment by basictheprogram** [comment]
On a fully patched Windows Server 2012 R2 the VCRUNTIME140.DLL dependencies are met by the UCRTBASE.DLL 

<img width="391" alt="chocolatey-test-environment_default_1514008433862_65284__running_" src="https://user-images.githubusercontent.com/6723257/34317476-6a2474d4-e775-11e7-8d5e-7427c8b4b0ff.png">

[File/Net](https://www.file.net/process/ucrtbase.dll.html) says this is part of the operating system.  I find it in the usual locations on a patched Windows Server 2012 R2. It is not found in "ferventcoder/win2012r2-x64-nocm".  

Comes back to using unpatched and old version of Windows Server 2012 R2 in chocolatey-test-environment.

**Comment by basictheprogram** [comment]
Full patched Windows10, draftsight 2018 installs, but Dependency Walker shows 

<img width="325" alt="stefan-schere-packer-windows_vagrant-windows-10_1514012650291_3235__running_" src="https://user-images.githubusercontent.com/6723257/34317919-ae9e3604-e77f-11e7-8435-24b59f932b76.png">

Not sure if the VCRUNTIME is the problem now.

I don't want to make a dependency on vcredist2015 if patched windows doesn't need this additional software installed. 

I'd rather ask for an exemption and save the disk space, clutter, and the bandwidth required to install vcredist2015 on all my updated Window installations.

**Comment by basictheprogram** [comment]
Add info the official forums: https://forum.solidworks.com/thread/213394

**Comment by teknowledgist** [comment]
@basictheprogram, I can put in a request to the admins at chocolatey.org for an exemption from the package verifier because any "normal" system should not have an issue with the package.  Alternatively, we can wait to see (and press) if there is a more comprehensive answer from SolidWorks on what the actual requirements.  (I suppose there is a third choice of pressing for the verifier to be updated, but that seems ancillary.) 

I see merits in both options (and don't have an urgent need for a new package version), so I'm letting you decide.

**Comment by basictheprogram** [comment]
I've opened a ticket with Dassault Systèmes lets see if they can help.

**Comment by teknowledgist** [comment]
@basictheprogram, Have you gotten any assistance from Dassault?  

DraftSight 2018 SP1 is out now.  I can update and push the package (with or without a vcredist dependency) and request an exemption from the verifier, or we can wait.

**Comment by basictheprogram** [comment]
I did get a response from 3rd party on Jan 19th.  We get support from 3rd party, but they could not answer my questions so I got sent directly to Dassault and I'm still waiting for them to answer my questions.

**Comment by teknowledgist** [comment]
I requested an exemption from automatic verification testing for Draftsight to the Chocolatey public repository admins.
