### ISSUE TITLE
Please add matlab 2020, 2021, 2022

### ISSUE THREAD

**Issue by AntoineD** [teknowledgist/Chocolatey-packages#80]

**Comment by teknowledgist** [comment]
I just submitted packages for MATLAB Runtime Compiler 2020b, 2021b, 2022b.  Assuming they pass automated testing and moderation (which can take a couple weeks), they should be available soonish.  You can install them before moderation approval using the `--version <package version>` switch in your Chocolatey install command.

If you need any of the specific "a" releases, let me know.

**Comment by AntoineD** [comment]
Thanks you!
