### ISSUE TITLE
Draftsight 2017 SP3 and 2018 SP0 urls broken

### ISSUE THREAD

**Issue by jedfrechette** [teknowledgist/Chocolatey-packages#9]
The download links for the approved 2017 SP3 package on Chocolatey-packages and the updated 2018 SP0 package in this repo no longer work. Presumably these changed when 2018 SP1 was released.

**Comment by teknowledgist** [comment]
I have submitted an updated package for v2018.01 (2018 SP1).  I don't have much hope that it will pass the automated testing, but it gives determined users the options to try.
