### ISSUE TITLE
[Barrier]

### ISSUE THREAD

**Issue by zippydan** [teknowledgist/Chocolatey-packages#90]
An annoying thing about this package is that it seems to install Visual C++ Redistributable 2017 (vcredist2017), even though I already have the comprehensive Visual C++ Redistributable 2015 - 2022 package (vcredist140) installed, which already includes 2015, 2017, 2019, and 2022 Redistributable packages.

This either needs a switch to choose your preferred VC Redistributable package, or to not install any at all, or it needs to check if vcredist140 is already installed.

**Comment by teknowledgist** [comment]
Hi.  Without digging into the history, I believe the `vcredist140` package was not comprehensive the last time Barrier was updated.  I've changed the dependency to `vcredist140`, and noted that [Barrier is no longer maintained](https://github.com/input-leap/input-leap/issues/1414).  I'll keep an eye on the replacement [Input-Leap](https://github.com/input-leap/input-leap) to create a Chocolatey package when possible.

Thanks.
