### ISSUE TITLE
`nessus-agent` outdated

### ISSUE THREAD

**Issue by elliot** [teknowledgist/Chocolatey-packages#97]
Package id: `nessus-agent`

Current package version: `10.5.0`
Version to update to: `10.5.1`

See: https://www.tenable.com/downloads/nessus-agents

Old package downloads no longer available

**Comment by teknowledgist** [comment]
Updated package has been submitted for moderation.  Thanks for the heads up.

**Comment by elliot** [comment]
Thanks @teknowledgist
