### ISSUE TITLE
(vstor2010) outdated

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [teknowledgist/Chocolatey-packages#99]
Package id: vstor2010

Current package version: 10.0.60910
Version to update to: 10.0.60912

**Comment by teknowledgist** [comment]
@TheCakeIsNaOH Where did you find the new version?  The version and checksum from [the official source](https://www.microsoft.com/en-us/download/details.aspx?id=105522) still match the current package, so I'm not sure where to look.  Thanks!

**Comment by TheCakeIsNaOH** [comment]
Actually, the latest version is v10.0.60917:
https://learn.microsoft.com/en-us/visualstudio/vsto/visual-studio-tools-for-office-runtime?view=vs-2022
https://www.microsoft.com/en-us/download/details.aspx?id=105890
https://download.microsoft.com/download/5/d/2/5d24f8f8-efbb-4b63-aa33-3785e3104713/vstor_redist.exe

**Comment by teknowledgist** [comment]
Well, that's embarrassing. A search for "vstor2010" took me to the link I had.  Thanks Microsoft!  

The release/support table you gave me allowed me to automate this package though, so thank you!

Updated version submitted.

**Comment by TheCakeIsNaOH** [comment]
Awesome, thanks for getting it updated.
